version: "3"
services:
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped     
    ports:
      - "5173:5173"
    networks:
      - app-network
    links:
      - server    
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "3001:3001"  
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
